stops = ["Croy", "Cumbernauld", "Falkirk High", "Linlithgow", "Livingston", "Haymarket"]
print(stops)
stops.append("Edinburgh Waverley")
print(stops)
stops.insert(0, "Glasgow Queen St")
print(stops)
stops.insert(4, "Polmont")
print(stops)
index = stops.index("Linlithgow")
print(index)
stops.remove("Livingston")
print(stops)
stops.pop(2)
print(stops)
print(len(stops))
stops.sort()
print(stops)
stops.sort(reverse = True)
print(stops)
for stop in stops:
    print(f"{stop}")